//
//  AIManager.swift
//  Explorer
//
//  Created by Lamar Williams III on 12/31/25.
//

import Foundation
import FoundationModels

actor AIManager {
  enum Results {
    case error(String)
    case success([ThingToDo])
  }

  @Generable(description: "A container for a list of items")
  struct ThingsToDo {
    @Guide(description: "A list of things to do", .count(6...10))
    let items: [ThingToDo]
  }

  @Generable(description: "A single item of things to do")
  struct ThingToDo {
    @Guide(description: "Name for this item")
    let name: String
    @Guide(description: "Address for this item")
    let address: String
    @Guide(description: "City for this item")
    let city: String
    @Guide(description: "State for this item")
    let state: String
    @Guide(description: "More information for this item")
    let otherInfo: String
  }

  let continuation: AsyncStream<Results>.Continuation
  let stream: AsyncStream<Results>

  init() {
    (stream, continuation) = AsyncStream.makeStream(of: Results.self)
  }

  func junk() async {
    let session = LanguageModelSession()
    do {
      let text = "Find a things to do near oakland, ca"
      let response = try await session.respond(to: text,
                                               generating: ThingsToDo.self)
      //    print("ljw response")
      //    print(response)
      print("ljw items")
      for item in response.content.items {
        print(item)
      }
      print("ljw items end --------------------------------")
    }
    catch LanguageModelSession.GenerationError.guardrailViolation(let error) {
      print("guardrailViolation Error")
      print(error)
      //    addMessage(
      //      """
      //      The system’s safety guardrails are triggered by content in a prompt or the response generated by the model.
      //      """,
      //      isFromUser: false
      //    )
    }
    catch LanguageModelSession.GenerationError.exceededContextWindowSize(let error) {
      print("exceededContextWindowSize Error")
      print(error)
      //    addMessage(
      //      "Context Windows Length of 4096 tokens has been exceeded.",
      //      isFromUser: false,
      //    )
    }
    catch {
      print("Error")
      print(error.localizedDescription)
    }



    /*
     ljw items
     ThingToDo(name: "Explore the Oakland Museum of California", address: "1901 Telegraph Ave, Oakland, CA 94612", city: "Oakland", state: "CA", otherInfo: "A museum showcasing California\'s natural and cultural history.")
     ThingToDo(name: "Visit the Oakland Zoo", address: "2100 Lakeshore Blvd, Oakland, CA 94610", city: "Oakland", state: "CA", otherInfo: "Home to a diverse collection of animals and beautiful gardens.")
     ThingToDo(name: "Walk along the East Bay Regional Park Trail", address: "Various locations in East Bay, CA", city: "Various", state: "CA", otherInfo: "A scenic trail offering views of the bay and city skyline.")
     ThingToDo(name: "Discover the Jack London Square", address: "2100 Broadway, Oakland, CA 94612", city: "Oakland", state: "CA", otherInfo: "A historic waterfront district with shops, restaurants, and events.")
     ThingToDo(name: "Tour the Fox Theatre", address: "1500 Broadway, Oakland, CA 94612", city: "Oakland", state: "CA", otherInfo: "A historic theater hosting performances and events.")
     ThingToDo(name: "Relax at Lakeside Park", address: "2100 Lakeshore Blvd, Oakland, CA 94610", city: "Oakland", state: "CA", otherInfo: "A beautiful park with walking paths and picnic areas.")
     ThingToDo(name: "Visit the Oakland Athletics Stadium", address: "1 Coliseum Blvd, Oakland, CA 94610", city: "Oakland", state: "CA", otherInfo: "Catch a game or explore the stadium\'s history.")
     ThingToDo(name: "Explore the Berkeley Marina", address: "1500 Broadway, Oakland, CA 94612", city: "Berkeley", state: "CA", otherInfo: "A vibrant marina with shops, eateries, and waterfront views.")
     ThingToDo(name: "Stroll through the Chabot Space and Science Center", address: "1000 Columbia Ave, Oakland, CA 94612", city: "Oakland", state: "CA", otherInfo: "An interactive science museum with exhibits and planetarium shows.")
     ThingToDo(name: "Enjoy the Ferry Building Marketplace", address: "800 Embarcadero, Oakland, CA 94612", city: "Oakland", state: "CA", otherInfo: "A food hall with diverse culinary options and local artisans.")
     ljw items end --------------------------------
     */

    //  func getCoordinates(from address: String) async throws -> CLLocationCoordinate2D? {
    //      // Create the request with the address string
    //    let request = MKGeocodingRequest(addressString: address)
    //
    //      // Execute the request
    //    let response = try await request?.mapItems.first
    //
    //      // Extract the coordinate from the first result
    //      return response.first?.placemark.coordinate
    //  }
    //
    //  // Usage Example
    //  let address = "1600 Amphitheatre Parkway, Mountain View, CA"
    //  getCoordinate(from: address) { (coordinate, error) in
    //      if let coordinate = coordinate {
    //          print("Latitude: \(coordinate.latitude), Longitude: \(coordinate.longitude)")
    //      } else if let error = error {
    //          print("Error: \(error.localizedDescription)")
    //      }
    //  }



    //  let searchRequest = MKLocalSearch.Request()
    //  searchRequest.naturalLanguageQuery = "Starbucks near me"
    ////  searchRequest.naturalLanguageQuery = "94611"
    //  // Optional: Define a specific region to search within
    //  // searchRequest.region = mapView.region
    //
    //  Task {
    //    do {
    //      let response = try await MKLocalSearch(request: searchRequest).start()
    //      for item in response.mapItems {
    //        print("----------------------------------")
    //        print("Name: \(item.name ?? "")")
    //        print("Address.description: \(item.address?.description)")
    //        print("Address.fullAddress: \(item.address?.fullAddress)")
    //        print("Address.shortAddress: \(item.address?.shortAddress)")
    //        let coordinate = item.location.coordinate
    //        print("Location: \(coordinate.latitude), \(coordinate.longitude)")
    //      }
    //    } catch {
    //      print("Search failed: \(error.localizedDescription)")
    //    }
    //  }
    //  ----------------------------------
    //  Name: Starbucks
    //  Address.description: Optional("<MKAddress: 0x60000023a640> {\n    fullAddress = \"13808 E 14th St, San Leandro, CA  94578, United States\";\n    shortAddress = \"13808 E 14th St, San Leandro\";\n}")
    //  Address.fullAddress: Optional("13808 E 14th St, San Leandro, CA  94578, United States")
    //  Address.shortAddress: Optional("13808 E 14th St, San Leandro")
    //  Location: 37.7147697, -122.14176
    //  ----------------------------------

  }
}

/*
 To find places for a specific activity like fishing in an iOS Swift app, you should use the MapKit framework and its MKLocalSearch functionality to query points of interest (POIs) based on the user's current location.
 Core Steps to Implement
 Import MapKit & CoreLocation: Needed for map display and user positioning.
 Request User Location: Use CLLocationManager to get the current coordinates.
 Perform MKLocalSearch: Use a natural language query like "fishing spot" or "boat ramp" within a defined region around the user.
 Display Results: Annotate the map with pins (MKMarkerAnnotationView) for found locations.
 Swift Code Example (SwiftUI)
 This example demonstrates searching for "fishing" near the user's current location:
 swift
 import SwiftUI
 import MapKit

 struct FishingSpotFinder: View {
     @State private var region = MKCoordinateRegion(
         center: CLLocationCoordinate2D(latitude: 37.7749, longitude: -122.4194),
         span: MKCoordinateSpan(latitudeDelta: 0.05, longitudeDelta: 0.05)
     )
     @State private var searchResults: [MKMapItem] = []

     var body: some View {
         Map(coordinateRegion: $region, annotationItems: searchResults) { item in
             MapMarker(coordinate: item.placemark.coordinate)
         }
         .onAppear {
             searchForFishingSpots()
         }
     }

     func searchForFishingSpots() {
         let request = MKLocalSearch.Request()
         // Keyword search for the activity
         request.naturalLanguageQuery = "fishing"
         request.region = region

         let search = MKLocalSearch(request: request)
         search.start { response, error in
             guard let response = response else {
                 print("Error: \(error?.localizedDescription ?? "Unknown error")")
                 return
             }
             searchResults = response.mapItems
         }
     }
 }
 Techniques to Improve Accuracy
 Refine the Query: Instead of just "fishing," use specific terms like "boat ramp," "fishing pier," or "lake" to find specialized locations.
 Filter by Region: Set the MKLocalSearch.Request.region to the visible area of the map to prevent results from being too far away.
 Use MKLocalSearchCompleter: Implement this to provide auto-complete suggestions as the user types.
 Third-Party APIs: For more specialized data (like water depth or species), consider integrating APIs from services like Fishbrain or Google Places, which offer specific filters for activity-based searches.
 */

/*
 import CoreLocation

 // 1. Define your coordinates
 let lat1 = 37.7749
 let lon1 = -122.4194 // San Francisco
 let lat2 = 34.0522
 let lon2 = -118.2437 // Los Angeles

 // 2. Create CLLocation objects
 let location1 = CLLocation(latitude: lat1, longitude: lon1)
 let location2 = CLLocation(latitude: lat2, longitude: lon2)

 // 3. Calculate the distance (returns meters as a Double)
 let distanceInMeters = location1.distance(from: location2)

 print("Distance: \(distanceInMeters) meters")
 print("Distance: \(distanceInMeters / 1000) kilometers")

 */

/*
 func generateImages() async throws {
   print("ljw \(Date()) \(#file):\(#function):\(#line)")
   do {
     print("ljw \(Date()) \(#file):\(#function):\(#line)")
     let creator = try await ImageCreator()
     print("ljw \(Date()) \(#file):\(#function):\(#line)")
     let generatedImages = creator.images(
//        for: [.text("A cat wearing mittens.")],
//        for: [.text("A beach in Hawaii")],
       for: [.text("An american football game")],
//        style: .illustration,
//        style: .animation,
       style: .sketch,
       limit: 1
     )

     for try await generatedImage in generatedImages {
       print("ljw \(Date()) \(#file):\(#function):\(#line)")
       images.append(generatedImage.cgImage)
     }
   } catch {
     print("error=\(error)")
   }
   print("ljw \(Date()) \(#file):\(#function):\(#line)")
 }

 */
